### ISSUE TITLE
Example Usage?

### ISSUE THREAD

**Issue by thebitguru** [mauriciobarroso/button#1]
Thank you for sharing this component.  Do you happen to have any example usage code?  If not, I can help create some for quicker usage.

**Comment by mauriciobarroso** [comment]
Hi @thebitguru, thanks for your offer, but first I need to improve the component code.

The usage of this component is as follows:
1. Include component header file
`#include "button.h"`
2. Create an instance of the component
`static button_t button;`
3. Define a FreeRTOS task to handle button events
```
static void buttonEventsTask(void * arg) {
	EventBits_t bits;
	const EventBits_t bitsWaitFor = (BUTTON_SHORT_PRESS_BIT |
							    BUTTON_MEDIUM_PRESS_BIT |
							    BUTTON_LONG_PRESS_BIT);

	for(;;) {
		/* Wait until some bit is set */
		bits = xEventGroupWaitBits(button.eventGroup, bitsWaitFor, pdTRUE, pdFALSE, portMAX_DELAY);

		if(bits & BUTTON_SHORT_PRESS_BIT) {
			ESP_LOGI(TAG, "BUTTON_SHORT_PRESS_BIT set!");

			/* Write your function for the short press button event */
		}

		else if(bits & BUTTON_MEDIUM_PRESS_BIT) {
			ESP_LOGI(TAG, "BUTTON_MEDIUM_PRESS_BIT set!");

			/* Write your function for the medium press button event */
		}
		else if(bits & BUTTON_LONG_PRESS_BIT) {
			ESP_LOGI(TAG, "BUTTON_LONG_PRESS_BIT set!");

			/* Write your function for the long press button event */
		}
		else {
			ESP_LOGI(TAG, "Button unexpected Event");
		}
	}
}
```
4. Initialize button instance
`ESP_ERROR_CHECK(button_Init(&button));`
5. Create the FreeRTOS task defined in the step 3
`	xTaskCreate(buttonEventsTask, "Button Events Task", configMINIMAL_STACK_SIZE * 4, NULL, tskIDLE_PRIORITY + 2, NULL);`

**Comment by thebitguru** [comment]
Sounds good.  Thank you for sharing the usage example!

**Comment by thebitguru** [comment]
`BUTTON_LONG_PRESS_BIT` and other bits are defined as private in the code and not public, so the task doesn't have access to those.  Am I reading this right?

Any chance you can also share examples of how to use this with multiple buttons?  Would I need as many tasks as the number of buttons?

Lastly, any ideas on when you might publish the improvements that you mentioned?

**Comment by mauriciobarroso** [comment]
Hi @thebitguru. I updated the code and instructions to use the component. Please test it and tell me if you find any errors or if something is not clear

**Comment by mauriciobarroso** [comment]
To the question, yes, for each button component a FreeRTOS task is created. The priority and stack size are defined in the function initializer `button_init`

**Comment by thebitguru** [comment]
Thanks for the effort!  I am having issues with some other pieces in my code and will test this out as soon as I have those worked out.  Thanks, again!

**Comment by thebitguru** [comment]
I did notice some things with the code and will open a new issue for it.  We can close this issue because you have already added the example usage.  Thanks!
